app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)

class User(UserMixin,db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),unique=True,)
    email = db.Column(db.String(255), unique=True, index=True)
    pass_secure = db.Column(db.String(255))
    posts = db.relationship('Post', backref='user', lazy='dynamic')
    comment = db.relationship('Comment', backref='post', lazy='dynamic')
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def save_user(self):
        db.session.add(self)
        db.session.commit()


    def __repr__(self):
        return f'User {self.username}'

class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    author = db.Column(db.String(100), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def save_post(self):
        db.session.add(self)
        db.session.commit()

    def delete_post(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    comment = db.Column(db.Text(), nullable=False)

    def save(self):
        db.session.add(self)
        db.session.commit()

    def delete(self):
        db.session.delete(self)
        db.session.commit()

    def __repr__(self):
        return f'Comments: {self.comment}'

class Quote:
    def __init__(self,quote,author):
        self.quote = quote
        self.author = author

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField, SelectField
from wtforms.validators import Required

class PostForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    content = TextAreaField('Content', validators=[Required()])
    author = TextAreaField('Author', validators=[Required()])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[Required()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Post')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail
from flask_simplemde import SimpleMDE
from flask_uploads import UploadSet, configure_uploads, IMAGES

bootstrap = Bootstrap()
db = SQLAlchemy()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
mail = Mail()
simple = SimpleMDE()
photos = UploadSet('photos', IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    #config_options[config_name].init_app(app)

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    simple.init_app(app)

    #Configure UploadSet
    configure_uploads(app, photos)
    mail.init_app(app)


    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    #auth
    from.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = '/authenticate')

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, error

app/main/views.py
from flask import render_template, redirect, url_for, flash, request, abort
from . import main
from flask_login import login_required, current_user
from .forms import PostForm, CommentForm, UpdateProfile
from ..models import Post, User, Comment
from .. import db, photos
from ..requests import get_quotes

@main.route('/')
def index():
    title = 'Home - Welcome to The Blogging Website'
    quote = get_quotes()
    posts_display = Post.query.all()
    return render_template('index.html', title=title, posts_display=posts_display, quote=quote)

@main.route('/forms/blog', methods=['GET', 'POST'])
@login_required
def blogform():
    form = PostForm()
    if form.validate_on_submit():
        title = form.title.data
        content = form.content.data
        author = form.author.data
        user_id = current_user._get_current_object().id
        post_obj = Post(title=title, content=content, author = author,user_id = user_id)
        post_obj.save_post()
        return redirect(url_for('main.index'))
    return render_template('blog_form.html', form=form)

@main.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.author = form.author.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('main.index'))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
        form.author.data = post.author
    return render_template('blog_form.html', form=form)

@main.route("/post/<int:post_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.index'))

@main.route('/pitch/comments', methods = ['GET', 'POST'])
@login_required
def comments():
   form = CommentForm()
   comments = Comment.query.all()
   if form.validate_on_submit():
       comment = form.comment.data
       new_comment = Comment(comment = comment)
       new_comment.save()
       return redirect(url_for('main.comments'))

   return render_template('comment.html', form=form, comments=comments)

@main.route("/comment/<int:comment_id>/delete", methods=['GET', 'POST'])
@login_required
def delete_comm(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('Your comment has been deleted!', 'success')
    return redirect(url_for('main.comments'))

@main.route('/user/<uname>')
@login_required
def profile(uname):
    uname = current_user.username
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)
    return render_template('profile/profile.html', user=user)

@main.route('/user/<uname>/update_profile', methods=['POST', 'GET'])
@login_required
def update_profile(uname):
    form = UpdateProfile()
    user = User.query.filter_by(username=uname).first()
    if user is None:
        abort(404)
    if form.validate_on_submit():
        user.bio = form.bio.data
        user.save_user()
        return redirect(url_for('.profile', uname=user.username))
    return render_template('profile/update.html', form=form, uname=uname)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block styles%}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}"/>
    {% endblock %}
    <title>Document</title>
</head>
<body>
{% block navbar%}
{% include "navbar.html" %}
{% endblock %}

{% block content%}

{% endblock %}

</body>
</html>

app/templates/blog_form.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8" style="border:5px solid grey; margin-top:50px; padding:30px">{{wtf.quick_form(form)}}</div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock%}

app/templates/comment.html
{% extends 'base.html'%}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8" style="border:5px solid rgb(166, 166, 166); margin-top:50px; padding:30px">{{wtf.quick_form(form)}}</div>
        <div class="col-md-2"></div>
    </div>

    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10" style="">
            <h1 style="text-decoration: underline; font-size:45px; text-align:center; margin-top:55px; margin-bottom:30px; ">Comments</h1>

            <div class="container">
                <div class="card-group" style=" ">
                    {% for comment in comments %}
                    <div class="card" style="min-width: 80vh; max-width:130vh; background-color:rgb(238, 238, 238); margin-bottom:30px">
                        <div class="card-header" style="background-color:rgb(188, 188, 188)"></div>
                        <div class="card-body"><p class="card-text" style="font-size:20px;">{{ comment.comment }}</p></div>
                        <div><a href= "{{url_for('main.delete_comm', comment_id=comment.id)}}" class="btn btn-grey btn-sm" id="delbtn">Delete</a></div>
                    </div>


                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>

{% endblock%}

app/templates/fourOwfour.html
{% extends 'base.html'%}

{% block content %}
<h1>WHOOOPS we can't find that page</h1>
<P>Go back to the <a href = "/">Home Page</a></P>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
{% endblock %}

{% block content %}
<div class="bgimage">
    <blockquote class="blockquote text-center" style="padding-top:45px; padding-left:30px; padding-right:30px">
        <p class="mb-4" style="color:white; font-size:30px">{{quote.quote}}</p>
        <footer class="blockquote-footer" style="font-weight:bold; font-size:25px; color:darkcyan;"><cite>{{quote.author}}</cite></footer>
    </blockquote>
</div>

<!--Flash Message-->
{% for message in get_flashed_messages() %}
<div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{message}}
</div>
{% endfor %}
<div class="container">
    <div class="card-group">
        {% for post in posts_display %}
        <div class="card" style="min-width: 80vh; max-width:130vh ;margin-left: 70px;margin-top: 30px; margin-bottom: 30px;margin-right: 20px ;align-content:center; padding:10px">
            <div class="post-preview">
                <h2 class="post-title" style="">{{post.title}}</h2>
                <p class="post-subtitle" style="font-size:20px">{{post.content}}</p>
                <p class="post-meta">Posted by {{post.author}} on {{post.date_posted.strftime('%B %d, %Y')}}</p>
                <a href= "{{url_for('main.comments')}}" class="btn btn-outline-info">Comment</a>
                <a href= "{{url_for('main.update_post', post_id=post.id)}}" class="btn btn-outline-info">Update</a>
                <a href= "{{url_for('main.delete_post', post_id=post.id)}}" class="btn btn-dark btn-sm">Delete</a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container">
        <a class="navbar-brand" href="/">Home</a>
        <button
                class="navbar-toggler navbar-toggler-right"
                type="button"
                data-toggle="collapse"
                data-target="#navbarToggler"
                aria-controls="navbarToggler"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon text-black"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto mb-2 mb-lg-0">


            </ul>

            <ul class="navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('main.blogform')}}">New Post</a>
                </li>
                {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a href="{{url_for('main.profile',uname=current_user.username)}}" class="nav-link">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="{{url_for('auth.logout')}}" class="nav-link">Sign out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a href="{{url_for('auth.login')}}" class="nav-link">Sign in</a>
                </li>
                {%endif%}
            </ul>
        </div>
    </div>
</nav>

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
    <div class="row">
        <!--Flash Message-->
        {% for message in get_flashed_messages() %}
        <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{message}}
        </div>
        {% endfor %}
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            <a href="{{url_for('main.update_profile', uname = user.username)}}" style="text-decoration:none" >Edit profile</a>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            <a href="{{url_for('main.update_profile', uname = user.username)}}" style="text-decoration:none" >Edit profile</a>

            {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">

            {% if user.profile_pic_path %}
            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {%else%}
            <p>No profile picture</p>
            {% endif %}

            {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
                <input type="file"  name="photo" class="form-control" required>
                <input type="submit">
                {% endif %}
            </form>

        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container mt-2">
    <!--Flash Message-->
    {% for message in get_flashed_messages() %}
    <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{message}}
    </div>
    {% endfor %}
    {{wtf.quick_form(form)}}
</div>
{% endblock %}